import Head from 'next/head';
import React, { useState } from 'react';
import {
  MDBContainer,
  MDBNavbar,
  MDBNavbarBrand,
  MDBNavbarToggler,
  MDBIcon,
  MDBNavbarNav,
  MDBNavbarItem,
  MDBNavbarLink,
  MDBCollapse,
} from 'mdb-react-ui-kit';
import { IsCurrentPageName } from '/utilities/common';

export const getMDBNavbarItem = (pageName, linkText) => {
  let navLink = IsCurrentPageName(pageName) ?
    <MDBNavbarLink active href={`/${pageName}`}>{linkText}</MDBNavbarLink> :
    <MDBNavbarLink href={`/${pageName}`}>{linkText}</MDBNavbarLink>;
  return (
    <MDBNavbarItem>
        {navLink}
    </MDBNavbarItem>
  );
}

export default function Header() {
  const [showNav, setShowNav] = useState(false);
  console.log(IsCurrentPageName("resume").toString());
  return (
    <>
      <Head>
        <title>Patrick J Thompson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
      </Head>
      <MDBNavbar expand='md' light bgColor='light'>
        <MDBNavbarBrand href='/' className="h1 mx-2 text-primary">Pat Thompson</MDBNavbarBrand>
        <MDBContainer fluid>
          <MDBNavbarToggler
            type='button'
            aria-expanded='false'
            aria-label='Toggle navigation'
            onClick={() => setShowNav(!showNav)}
          >
            <MDBIcon icon='bars' fas />
          </MDBNavbarToggler>
          <MDBCollapse navbar show={showNav}>
            <MDBNavbarNav>
              {getMDBNavbarItem("metaverse", "MetaVerse")}
              <MDBNavbarItem>
                <MDBNavbarLink aria-current={IsCurrentPageName("projects").toString()} href='/projects'>
                  Projects
                </MDBNavbarLink>
              </MDBNavbarItem>
              <MDBNavbarItem>
                <MDBNavbarLink aria-current={IsCurrentPageName("writing").toString()} href='/writing'>
                  Writing
                </MDBNavbarLink>
              </MDBNavbarItem>
              <MDBNavbarItem>
                <MDBNavbarLink aria-current={IsCurrentPageName("employers").toString()} href='/employers'>
                  Employers
                </MDBNavbarLink>
              </MDBNavbarItem>
            </MDBNavbarNav>
          </MDBCollapse>
        </MDBContainer>
      </MDBNavbar>
    </>
  );
}
