import Head from 'next/head';
import React, { useState } from 'react';
import {
  MDBContainer,
  MDBNavbar,
  MDBNavbarBrand,
  MDBNavbarToggler,
  MDBIcon,
  MDBNavbarNav,
  MDBNavbarItem,
  MDBNavbarLink,
  MDBCollapse,
} from 'mdb-react-ui-kit';
import { IsCurrentPageName } from '/utilities/common';

export default function Header() {
  const [showBasic, setShowBasic] = useState(false);

  return (
    <div className="">

      <Head>
        <title>Patrick J Thompson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
      </Head>
      
      <MDBNavbar expand='md' light bgColor='light'>
        <MDBContainer fluid>
          <MDBNavbarBrand href='/' className="text-primary">Pat Thompson</MDBNavbarBrand>

          <MDBNavbarToggler
            aria-controls='navbarSupportedContent'
            aria-expanded='false'
            aria-label='Toggle navigation'
            onClick={() => setShowBasic(!showBasic)}
          >
            <MDBIcon icon='bars' fas />
          </MDBNavbarToggler>

          <MDBCollapse navbar show={showBasic}>
            <MDBNavbarNav className='mr-auto mb-2 mb-lg-0 text-secondary'>
              
              <MDBNavbarItem>
                <MDBNavbarLink active aria-current={IsCurrentPageName("resume").toString()} href='resume'>
                  Interactive Resumé
                </MDBNavbarLink>
              </MDBNavbarItem>

              <MDBNavbarItem>
                <MDBNavbarLink active aria-current={IsCurrentPageName("projects").toString()} href='projects'>
                  Projects
                </MDBNavbarLink>
              </MDBNavbarItem>

              <MDBNavbarItem>
                <MDBNavbarLink active aria-current={IsCurrentPageName("writing").toString()} href='writing'>
                  Writing
                </MDBNavbarLink>
              </MDBNavbarItem>
              
            </MDBNavbarNav>
          </MDBCollapse>
        </MDBContainer>
      </MDBNavbar>

    </div>
  );
}
