import Head from 'next/head';
import React, { useState } from 'react';
import {
  MDBContainer,
  MDBNavbar,
  MDBNavbarBrand,
  MDBNavbarToggler,
  MDBIcon,
  MDBNavbarNav,
  MDBNavbarItem,
  MDBNavbarLink,
  MDBCollapse,
} from 'mdb-react-ui-kit';
import { IsCurrentPageName } from '/utilities/common';

export default function Header() {
  const [showNav, setShowNav] = useState(false);
  return (
    <>
      <Head>
        <title>Patrick J Thompson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
      </Head>
      <MDBNavbar expand='md' light bgColor='light'>
        <MDBNavbarBrand href='/' className="h1 mx-2 text-primary">Pat Thompson</MDBNavbarBrand>
        <MDBContainer fluid>
          <MDBNavbarToggler
            type='button'
            aria-expanded='false'
            aria-label='Toggle navigation'
            onClick={() => setShowNav(!showNav)}
          >
            <MDBIcon icon='bars' fas />
          </MDBNavbarToggler>
          <MDBCollapse navbar show={showNav}>
            <MDBNavbarNav>
              <MDBNavbarItem>
                <MDBNavbarLink aria-current={IsCurrentPageName("resume").toString()} href='/resume'>
                  Interactive Resumé
                </MDBNavbarLink>
              </MDBNavbarItem>
              <MDBNavbarItem>
                <MDBNavbarLink aria-current={IsCurrentPageName("projects").toString()} href='/projects'>
                  Projects
                </MDBNavbarLink>
              </MDBNavbarItem>
              <MDBNavbarItem>
                <MDBNavbarLink aria-current={IsCurrentPageName("writing").toString()} href='/writing'>
                  Writing
                </MDBNavbarLink>
              </MDBNavbarItem>
              <MDBNavbarItem>
                <MDBNavbarLink aria-current={IsCurrentPageName("employers").toString()} href='/employers'>
                  Employers
                </MDBNavbarLink>
              </MDBNavbarItem>
            </MDBNavbarNav>
          </MDBCollapse>
        </MDBContainer>
      </MDBNavbar>
    </>
  );
}

function AltHeader(){
  return (
    <>
    <MDBNavbarToggler
      type='button'
      aria-expanded='false'
      aria-label='Toggle navigation'
      onClick={() => setShowNav(!showNav)}
    >
      <MDBIcon icon='bars' fas />
    </MDBNavbarToggler>
    <MDBCollapse navbar show={showNav}>
      <MDBNavbarNav>
        <MDBNavbarItem>
          <MDBNavbarLink active aria-current='page' href='#'>
            Home
          </MDBNavbarLink>
        </MDBNavbarItem>
        <MDBNavbarItem>
          <MDBNavbarLink href='#'>Features</MDBNavbarLink>
        </MDBNavbarItem>
        <MDBNavbarItem>
          <MDBNavbarLink href='#'>Pricing</MDBNavbarLink>
        </MDBNavbarItem>
        <MDBNavbarItem>
          <MDBNavbarLink disabled href='#' tabIndex={-1} aria-disabled='true'>
            Disabled
          </MDBNavbarLink>
        </MDBNavbarItem>
      </MDBNavbarNav>
    </MDBCollapse>
    </>
  );
}
